Repository PICK-PLE/PICKPLE-server, pull requests merged in 2024-08, with the labels that each got.

#122 [fix] 호스트 마이페이지 500 에러 해결
  src/main/java/com/pickple/server/global/common/annotation/resolver/HostIdResolver.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
Labels: fix, 🦊 예린

#126 [feat] requestDto에 RedirectUri 담도록 구현
  src/main/java/com/pickple/server/global/auth/client/dto/UserLoginRequest.java
  src/main/java/com/pickple/server/global/auth/client/kakao/KakaoSocialService.java
Labels: 🐰 보람, feat

#125 [refactor] 유효성 검증 로직 리팩토링
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/DateInfo.java
  src/main/java/com/pickple/server/api/moim/dto/request/MoimCreateRequest.java
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/request/MoimSubmitRequest.java
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterController.java
  src/main/java/com/pickple/server/api/submitter/dto/request/SubmitterCreateRequest.java
Labels: refactor, 🦊 예린

#130 [refactor] 카테고리 조회 로직 위치 변경
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/enums/Category.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
Labels: refactor, 🐱 예린

#133 [refactor] 신청자 승인 시 상태값 변경 로직 리팩토링
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
Labels: refactor, 🐱 예린

#135 [refactor] 관리자권한 관리 방식 수정
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterController.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterCommandService.java
  src/main/java/com/pickple/server/api/user/domain/Role.java
  src/main/java/com/pickple/server/api/user/domain/User.java
  src/main/java/com/pickple/server/api/user/service/UserService.java
  src/main/java/com/pickple/server/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/pickple/server/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/pickple/server/global/auth/security/CustomAccessDeniedHandler.java
  src/main/java/com/pickple/server/global/config/SecurityConfig.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
Labels: refactor, 🐰 보람

#137 [feat] 누락된 api들 유효성 검증 추가
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/request/MoimSubmitterUpdateRequest.java
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
  src/main/java/com/pickple/server/api/user/controller/UserController.java
  src/main/java/com/pickple/server/global/auth/client/dto/UserLoginRequest.java
Labels: 🐰 보람, feat

#141 [feat] 공지사항 삭제 API 구현
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
  src/main/java/com/pickple/server/api/notice/repository/NoticeRepository.java
  src/main/java/com/pickple/server/api/notice/service/NoticeCommandService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐱 예린, feat

#143 [feat] 호스트 승인신청 및 승인 시 2차 스프린트 로직 반영
  src/main/java/com/pickple/server/api/host/domain/Host.java
  src/main/java/com/pickple/server/api/host/dto/response/HostByMoimResponse.java
  src/main/java/com/pickple/server/api/host/dto/response/HostGetResponse.java
  src/main/java/com/pickple/server/api/host/service/HostQueryService.java
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterController.java
  src/main/java/com/pickple/server/api/submitter/domain/Submitter.java
  src/main/java/com/pickple/server/api/submitter/dto/request/SubmitterCreateRequest.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterCommandService.java
Labels: 🐰 보람, feat

#148 [feat] 공지사항 작성 시 2차 스프린트 로직 반영
  src/main/java/com/pickple/server/api/host/domain/Host.java
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
  src/main/java/com/pickple/server/api/notice/domain/Notice.java
  src/main/java/com/pickple/server/api/notice/dto/request/NoticeCreateRequest.java
  src/main/java/com/pickple/server/api/notice/service/NoticeCommandService.java
  src/main/java/com/pickple/server/api/submitter/domain/Submitter.java
  src/main/java/com/pickple/server/api/submitter/dto/request/SubmitterCreateRequest.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterCommandService.java
Labels: 🐰 보람, feat

#151 [feat] 리뷰 태그 전체 조회 api 구현
  src/main/java/com/pickple/server/api/review/Service/ReviewQueryService.java
  src/main/java/com/pickple/server/api/review/controller/ReviewController.java
  src/main/java/com/pickple/server/api/review/controller/ReviewControllerDocs.java
  src/main/java/com/pickple/server/api/review/domain/enums/HostTag.java
  src/main/java/com/pickple/server/api/review/domain/enums/MoimTag.java
  src/main/java/com/pickple/server/api/review/dto/response/TagListGetResponse.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐰 보람, feat

#153 [feat] 호스트 정보 조회 api 2차 스프린트 로직 반영
  src/main/java/com/pickple/server/api/host/controller/HostController.java
  src/main/java/com/pickple/server/api/host/dto/response/HostGetResponse.java
  src/main/java/com/pickple/server/api/host/service/HostQueryService.java
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
Labels: 🐰 보람, feat

#139 [feat] 모임 진행 상태 스케줄러 추가
  src/main/java/com/pickple/server/PickpleServerApplication.java
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
Labels: 🐱 예린, feat

#158 [refactor] presiginedUrl 요청 방식 리팩토링
  src/main/java/com/pickple/server/global/common/external/s3/S3Controller.java
  src/main/java/com/pickple/server/global/common/external/s3/S3ControllerDocs.java
  src/main/java/com/pickple/server/global/common/external/s3/S3Service.java
  src/main/java/com/pickple/server/global/common/external/s3/controller/S3Controller.java
  src/main/java/com/pickple/server/global/common/external/s3/controller/S3ControllerDocs.java
  src/main/java/com/pickple/server/global/common/external/s3/dto/PreSignedUrlClientRequest.java
  src/main/java/com/pickple/server/global/common/external/s3/dto/PreSignedUrlResponse.java
Labels: 🐰 보람, feat

#162 [feat] 호스트 소개 조회 API 구현
  src/main/java/com/pickple/server/api/host/controller/HostController.java
  src/main/java/com/pickple/server/api/host/controller/HostControllerDocs.java
  src/main/java/com/pickple/server/api/host/dto/response/HostIntroGetResponse.java
  src/main/java/com/pickple/server/api/host/service/HostQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐰 보람, feat

#160 [feat] 모임 참여 신청 내역 전체 조회 api 구현
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionControllerDocs.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/MoimSubmissionAllResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/global/config/SecurityConfig.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐰 보람, feat, Need to Refactor

#165 [feat] 공지사항 상세 조회 API 구현
  src/main/java/com/pickple/server/api/comment/repository/CommentRepository.java
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
  src/main/java/com/pickple/server/api/notice/dto/response/NoticeDetailGetResponse.java
  src/main/java/com/pickple/server/api/notice/service/NoticeQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐱 예린, feat

#168 [feat] 공지사항 전체 조회 시 2차 스프린트 로직 반영
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
  src/main/java/com/pickple/server/api/notice/dto/response/NoticeListGetByMoimResponse.java
  src/main/java/com/pickple/server/api/notice/service/NoticeQueryService.java
Labels: 🐰 보람, feat

#169 [feat] 공지사항에 해당하는 댓글 전체 조회 API 구현
  src/main/java/com/pickple/server/api/comment/controller/CommentController.java
  src/main/java/com/pickple/server/api/comment/controller/CommentControllerDocs.java
  src/main/java/com/pickple/server/api/comment/domain/CommenterInfo.java
  src/main/java/com/pickple/server/api/comment/dto/response/CommentGetResponse.java
  src/main/java/com/pickple/server/api/comment/repository/CommentRepository.java
  src/main/java/com/pickple/server/api/comment/service/CommentQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐱 예린, feat

#171 [feat] 게스트에 해당하는 참가한 모임 조회 API 2차 스프린트 반영
  src/main/java/com/pickple/server/api/moim/dto/response/SubmittedMoimByGuestResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
Labels: 🐱 예린, feat

#173 [feat] 게스트 프로필 수정 API 구현
  src/main/java/com/pickple/server/api/guest/controller/.gitkeep
  src/main/java/com/pickple/server/api/guest/controller/GuestController.java
  src/main/java/com/pickple/server/api/guest/domain/Guest.java
  src/main/java/com/pickple/server/api/guest/dto/.gitkeep
  src/main/java/com/pickple/server/api/guest/dto/request/GuestUpdateRequest.java
  src/main/java/com/pickple/server/api/guest/repository/GuestRepository.java
  src/main/java/com/pickple/server/api/guest/service/.gitkeep
  src/main/java/com/pickple/server/api/guest/service/GuestCommandService.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterCommandService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐱 예린, feat
