Repository PICK-PLE/PICKPLE-server, pull requests merged in 2024-10, with the labels that each got.

#244 [fix] 모임에 해당하는 신청자 전체 조회 api 및 에러 수정
  src/main/java/com/pickple/server/api/host/service/HostQueryService.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
Labels: fix, 🐰 보람

#246 [fix] 모임 승인 가능 여부 판단 로직 수정 및 승인 인원 count 로직 수정
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
Labels: fix, 🐰 보람

#250 [fix] 리뷰 조회 api 정렬 추가 및 repository 메소드명 컨벤션 적용
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/api/notice/repository/NoticeRepository.java
  src/main/java/com/pickple/server/api/notice/service/NoticeQueryService.java
  src/main/java/com/pickple/server/api/review/Service/ReviewQueryService.java
  src/main/java/com/pickple/server/api/review/repository/ReviewRepository.java
  src/main/java/com/pickple/server/api/user/repository/UserRepository.java
  src/main/java/com/pickple/server/api/user/repository/UserRepositoryCustom.java
  src/main/java/com/pickple/server/api/user/service/UserService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
Labels: refactor, fix, 🐰 보람

#248 [hotfix] 모임 종료 시 모임 참여 신청 상태값 completed로 변경
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
Labels: hotfix, 🐱 예린
