Repository PICK-PLE/PICKPLE-server, pull requests merged in 2024-09, with the labels that each got.

#180 [feat] 호스트에 해당하는 리뷰 전체 조회 api 구현
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/notice/service/NoticeQueryService.java
  src/main/java/com/pickple/server/api/review/Service/ReviewQueryService.java
  src/main/java/com/pickple/server/api/review/controller/ReviewController.java
  src/main/java/com/pickple/server/api/review/controller/ReviewControllerDocs.java
  src/main/java/com/pickple/server/api/review/dto/response/ReviewListGetByHostResponse.java
  src/main/java/com/pickple/server/api/review/repository/ReviewRepository.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐰 보람, feat

#181 [feat] 모임에 해당하는 리뷰 전체 조회 api 구현
  src/main/java/com/pickple/server/api/review/Service/ReviewQueryService.java
  src/main/java/com/pickple/server/api/review/controller/ReviewController.java
  src/main/java/com/pickple/server/api/review/controller/ReviewControllerDocs.java
  src/main/java/com/pickple/server/api/review/dto/response/ReviewListGetByMoimResponse.java
  src/main/java/com/pickple/server/api/review/repository/ReviewRepository.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐰 보람, feat

#179 [feat] 공지사항 댓글 삭제 API 구현
  src/main/java/com/pickple/server/api/comment/controller/CommentController.java
  src/main/java/com/pickple/server/api/comment/controller/CommentControllerDocs.java
  src/main/java/com/pickple/server/api/comment/repository/CommentRepository.java
  src/main/java/com/pickple/server/api/comment/service/CommentCommandService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐱 예린, feat

#183 [fix] 모임 상태 전환 스케줄러 시간 변경
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/global/util/DateUtil.java
Labels: fix, 🐱 예린

#177 [feat] 호스트 프로필 수정 API 구현
  src/main/java/com/pickple/server/api/host/controller/HostController.java
  src/main/java/com/pickple/server/api/host/controller/HostControllerDocs.java
  src/main/java/com/pickple/server/api/host/domain/Host.java
  src/main/java/com/pickple/server/api/host/dto/request/HostUpdateRequest.java
  src/main/java/com/pickple/server/api/host/service/HostCommandService.java
  src/main/java/com/pickple/server/global/common/external/s3/S3BucketDirectory.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐱 예린, feat, Need to Refactor

#186 [refactor] submitter 엔티티 구조 변경
  src/main/java/com/pickple/server/api/submitter/domain/Submitter.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterCommandService.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterQueryService.java
Labels: refactor, 🐱 예린

#189 [fix] presigned Url request 수정
  src/main/java/com/pickple/server/global/common/external/s3/controller/S3Controller.java
Labels: fix, 🐰 보람

#193 [feat] 호스트에 해당하는 모임 조회 api 구현
  src/main/java/com/pickple/server/api/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/pickple/server/api/comment/dto/response/CommentGetResponse.java
  src/main/java/com/pickple/server/api/guest/dto/request/GuestUpdateRequest.java
  src/main/java/com/pickple/server/api/host/dto/response/HostByMoimResponse.java
  src/main/java/com/pickple/server/api/host/dto/response/HostIntroGetResponse.java
  src/main/java/com/pickple/server/api/host/dto/response/SubmittionDetailResponse.java
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/controller/MoimControllerDocs.java
  src/main/java/com/pickple/server/api/moim/dto/request/MoimCreateRequest.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimCreateResponse.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimDescriptionResponse.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimDetailResponse.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimListByHostAndMoimStateGetResponse.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimListByHostGetResponse.java
  src/main/java/com/pickple/server/api/moim/dto/response/SubmittedMoimByGuestResponse.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/request/MoimSubmitRequest.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/request/MoimSubmitterUpdateRequest.java
  src/main/java/com/pickple/server/api/notice/dto/request/NoticeCreateRequest.java
  src/main/java/com/pickple/server/api/notice/dto/response/NoticeDetailGetResponse.java
  src/main/java/com/pickple/server/api/notice/dto/response/NoticeListGetByMoimResponse.java
  src/main/java/com/pickple/server/api/review/dto/response/ReviewListGetByHostResponse.java
  src/main/java/com/pickple/server/api/review/dto/response/ReviewListGetByMoimResponse.java
  src/main/java/com/pickple/server/api/review/dto/response/TagListGetResponse.java
  src/main/java/com/pickple/server/api/submitter/dto/request/SubmitterCreateRequest.java
  src/main/java/com/pickple/server/api/user/dto/AccessTokenGetSuccess.java
  src/main/java/com/pickple/server/api/user/dto/LoginSuccessResponse.java
  src/main/java/com/pickple/server/api/user/dto/TokenDto.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐰 보람, feat, Need to Refactor

#191 [feat] 리뷰 작성 시 모임 정보 조회 API
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/controller/MoimControllerDocs.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimGetResponse.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
Labels: 🐱 예린, feat

#195 [feat] 게스트 프로필 조회 API 구현
  src/main/java/com/pickple/server/api/guest/controller/GuestController.java
  src/main/java/com/pickple/server/api/guest/controller/GuestControllerDocs.java
  src/main/java/com/pickple/server/api/guest/dto/response/GuestGetResponse.java
  src/main/java/com/pickple/server/api/guest/service/GuestQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 🐱 예린, feat

#197 [fix] 댓글 전체 조회 시 response에 댓글 Id값 추가
  src/main/java/com/pickple/server/api/comment/dto/response/CommentGetResponse.java
  src/main/java/com/pickple/server/api/comment/service/CommentQueryService.java
Labels: fix, 🐱 예린

#199 [fix] 호스트 승인 신청 내역 조회 API 수정
  src/main/java/com/pickple/server/api/submitter/dto/response/SubmitterListGetResponse.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterQueryService.java
Labels: fix, 🐱 예린

#201 [fix] 게스트에 해당하는 신청한 모임 조회 로직 수정
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
Labels: fix, 🐱 예린

#203 [fix] 공지사항에 해당하는 댓글 조회 시 시간 정보 추가
  src/main/java/com/pickple/server/api/comment/service/CommentQueryService.java
Labels: fix, 🐱 예린

#205 [fix] 공지사항 댓글 삭제 시 호스트 삭제 권한 추가
  src/main/java/com/pickple/server/api/comment/service/CommentCommandService.java
Labels: fix, 🐱 예린

#207 [fix] 공지사항 전체 조회 api 공개여부 로직 반영
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
  src/main/java/com/pickple/server/api/notice/controller/NoticeControllerDocs.java
  src/main/java/com/pickple/server/api/notice/service/NoticeQueryService.java
Labels: 🐰 보람, feat, Need to Refactor

#209 [fix] 호스트 정보 수정 API 수정
  src/main/java/com/pickple/server/api/host/dto/request/HostUpdateRequest.java
  src/main/java/com/pickple/server/api/host/service/HostCommandService.java
Labels: fix, 🐱 예린

#211 [fix] 공지사항 전체조회 api 에러수정
  src/main/java/com/pickple/server/api/notice/controller/NoticeControllerDocs.java
  src/main/java/com/pickple/server/api/notice/service/NoticeQueryService.java
Labels: fix, 🐰 보람

#213 [feat] 호스트 정보 조회 api 에러상황 추가
  src/main/java/com/pickple/server/api/host/controller/HostController.java
  src/main/java/com/pickple/server/api/host/controller/HostControllerDocs.java
  src/main/java/com/pickple/server/api/host/service/HostQueryService.java
  src/main/java/com/pickple/server/api/moim/controller/MoimControllerDocs.java
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterControllerDocs.java
  src/main/java/com/pickple/server/api/submitter/repository/SubmitterRepository.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
Labels: 🐰 보람, feat

#219 [fix] 프로필 수정 시 닉네임 중복검사 로직 변경
  src/main/java/com/pickple/server/api/guest/service/GuestCommandService.java
  src/main/java/com/pickple/server/api/host/service/HostCommandService.java
  src/main/java/com/pickple/server/api/submitter/repository/SubmitterRepository.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterCommandService.java
Labels: fix, 🐰 보람, Need to Refactor

#221 [fix] 카테고리 전체조회 api 2차 스프린트 반영
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/enums/Category.java
Labels: fix, 🐰 보람

#223 [feat] 베테랑 스티커를 위한 response 추가 및 수정
  gradlew
  src/main/java/com/pickple/server/api/comment/domain/CommenterInfo.java
  src/main/java/com/pickple/server/api/guest/domain/Guest.java
  src/main/java/com/pickple/server/api/host/controller/HostController.java
  src/main/java/com/pickple/server/api/host/controller/HostControllerDocs.java
  src/main/java/com/pickple/server/api/host/domain/Host.java
  src/main/java/com/pickple/server/api/host/domain/HostCategoryInfo.java
  src/main/java/com/pickple/server/api/host/dto/response/HostByMoimResponse.java
  src/main/java/com/pickple/server/api/host/dto/response/HostGetResponse.java
  src/main/java/com/pickple/server/api/host/dto/response/HostIntroGetResponse.java
  src/main/java/com/pickple/server/api/host/service/HostQueryService.java
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/domain/enums/Category.java
  src/main/java/com/pickple/server/api/moim/domain/enums/MoimState.java
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/AccountInfo.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/AnswerInfo.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmission.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmissionState.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/SubmitterInfo.java
  src/main/java/com/pickple/server/api/review/domain/Review.java
  src/main/java/com/pickple/server/api/review/domain/enums/HostTag.java
  src/main/java/com/pickple/server/api/review/domain/enums/MoimTag.java
  src/main/java/com/pickple/server/api/submitter/domain/Submitter.java
  src/main/java/com/pickple/server/api/submitter/domain/SubmitterCategoryInfo.java
  src/main/java/com/pickple/server/api/submitter/domain/SubmitterState.java
Labels: 🐰 보람, feat

#225 [feat] 모임에 해당하는 공지사항 전체 조회 api response에 공개여부 추가
  src/main/java/com/pickple/server/api/comment/service/CommentQueryService.java
  src/main/java/com/pickple/server/api/notice/dto/response/NoticeListGetByMoimResponse.java
  src/main/java/com/pickple/server/api/notice/service/NoticeQueryService.java
Labels: 🐰 보람, feat

#227 [feat] 댓글 관련 베테랑 스티커를 위한 response 추가
  src/main/java/com/pickple/server/api/comment/dto/response/CommentGetResponse.java
  src/main/java/com/pickple/server/api/comment/service/CommentQueryService.java
Labels: 🐰 보람, feat

#231 [fix] 댓글 전체 조회 api 에서 베테랑 여부 제거
  src/main/java/com/pickple/server/api/comment/dto/response/CommentGetResponse.java
  src/main/java/com/pickple/server/api/comment/service/CommentQueryService.java
Labels: fix, 🐰 보람

#233 [fix] 모임 상태와 isOngoing 필드값 동기화되도록 수정
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/global/util/DateUtil.java
Labels: fix, 🐱 예린, Need to Refactor

#235 [fix] 관리자 페이지 컬럼 추가
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/MoimSubmissionAllResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
Labels: fix, 🐱 예린

#239 [fix] 토큰 시간 수정
  src/main/java/com/pickple/server/global/auth/jwt/provider/JwtTokenProvider.java
Labels: fix, 🐰 보람

#241 [feat] all로 요청이 들어올 경우 모든 모임 반환 추가
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
Labels: 🐰 보람, feat
