Repository PICK-PLE/PICKPLE-server, pull requests merged in 2024-07, with the labels that each got.

#4 [setting] 에러 및 응답관련 초기셋팅
  build.gradle
  settings.gradle
  src/main/java/com/pickple/server/PickpleServerApplication.java
  src/main/java/com/pickple/server/api/.gitkeep
  src/main/java/com/pickple/server/api/TestController.java
  src/main/java/com/pickple/server/global/config/WebConfig.java
  src/main/java/com/pickple/server/global/exception/CustomException.java
  src/main/java/com/pickple/server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/pickple/server/global/exception/ResponseStatusSetterAdvice.java
  src/main/java/com/pickple/server/global/exception/enums/.gitkeep
  src/main/java/com/pickple/server/global/response/ApiResponse.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: setting, 보람

#7 [feat] kakao social login 구현
  build.gradle
  src/main/java/com/pickple/server/PickpleServerApplication.java
  src/main/java/com/pickple/server/api/TestController.java
  src/main/java/com/pickple/server/api/user/controller/UserController.java
  src/main/java/com/pickple/server/api/user/controller/UserControllerDocs.java
  src/main/java/com/pickple/server/api/user/domain/SocialType.java
  src/main/java/com/pickple/server/api/user/domain/User.java
  src/main/java/com/pickple/server/api/user/dto/AccessTokenGetSuccess.java
  src/main/java/com/pickple/server/api/user/dto/LoginSuccessResponse.java
  src/main/java/com/pickple/server/api/user/repository/UserRepository.java
  src/main/java/com/pickple/server/api/user/repository/UserRepositoryCustom.java
  src/main/java/com/pickple/server/api/user/service/UserService.java
  src/main/java/com/pickple/server/global/auth/client/dto/UserInfoResponse.java
  src/main/java/com/pickple/server/global/auth/client/dto/UserLoginRequest.java
  src/main/java/com/pickple/server/global/auth/client/kakao/KakaoApiClient.java
  src/main/java/com/pickple/server/global/auth/client/kakao/KakaoAuthApiClient.java
  src/main/java/com/pickple/server/global/auth/client/kakao/KakaoSocialService.java
  src/main/java/com/pickple/server/global/auth/client/kakao/response/KakaoAccessTokenResponse.java
  src/main/java/com/pickple/server/global/auth/client/kakao/response/KakaoAccount.java
  src/main/java/com/pickple/server/global/auth/client/kakao/response/KakaoUserProfile.java
  src/main/java/com/pickple/server/global/auth/client/kakao/response/KakaoUserResponse.java
  src/main/java/com/pickple/server/global/auth/client/service/SocialService.java
  src/main/java/com/pickple/server/global/auth/jwt/.gitkeep
  src/main/java/com/pickple/server/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/pickple/server/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/pickple/server/global/auth/jwt/provider/JwtValidationType.java
  src/main/java/com/pickple/server/global/auth/jwt/repository/TokenRepository.java
  src/main/java/com/pickple/server/global/auth/jwt/service/TokenService.java
  src/main/java/com/pickple/server/global/auth/redis/.gitkeep
  src/main/java/com/pickple/server/global/auth/redis/domain/Token.java
  src/main/java/com/pickple/server/global/auth/security/.gitkeep
  src/main/java/com/pickple/server/global/auth/security/CustomAccessDeniedHandler.java
  src/main/java/com/pickple/server/global/auth/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/pickple/server/global/auth/security/UserAuthentication.java
  src/main/java/com/pickple/server/global/config/RedisConfig.java
  src/main/java/com/pickple/server/global/config/SecurityConfig.java
  src/main/java/com/pickple/server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/pickple/server/global/exception/ResponseStatusSetterAdvice.java
  src/main/java/com/pickple/server/global/response/ApiResponseDto.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 보람, feat

#8 [setting] sentry 연동
  build.gradle
Labels: setting, 예린

#11 [feat] entity 구현
  src/main/java/com/pickple/server/PickpleServerApplication.java
  src/main/java/com/pickple/server/api/applicant/controller/.gitkeep
  src/main/java/com/pickple/server/api/applicant/domain/Submitter.java
  src/main/java/com/pickple/server/api/applicant/domain/SubmitterState.java
  src/main/java/com/pickple/server/api/applicant/dto/.gitkeep
  src/main/java/com/pickple/server/api/applicant/repository/.gitkeep
  src/main/java/com/pickple/server/api/applicant/service/.gitkeep
  src/main/java/com/pickple/server/api/guest/controller/.gitkeep
  src/main/java/com/pickple/server/api/guest/domain/Guest.java
  src/main/java/com/pickple/server/api/guest/dto/.gitkeep
  src/main/java/com/pickple/server/api/guest/repository/.gitkeep
  src/main/java/com/pickple/server/api/guest/service/.gitkeep
  src/main/java/com/pickple/server/api/host/controller/.gitkeep
  src/main/java/com/pickple/server/api/host/domain/Host.java
  src/main/java/com/pickple/server/api/host/dto/.gitkeep
  src/main/java/com/pickple/server/api/host/repository/.gitkeep
  src/main/java/com/pickple/server/api/host/service/.gitkeep
  src/main/java/com/pickple/server/api/moim/controller/.gitkeep
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/domain/enums/Category.java
  src/main/java/com/pickple/server/api/moim/domain/enums/MoimState.java
  src/main/java/com/pickple/server/api/moim/dto/.gitkeep
  src/main/java/com/pickple/server/api/moim/repository/.gitkeep
  src/main/java/com/pickple/server/api/moim/service/.gitkeep
  src/main/java/com/pickple/server/api/moimapplication/controller/.gitkeep
  src/main/java/com/pickple/server/api/moimapplication/domain/MoimSubmission.java
  src/main/java/com/pickple/server/api/moimapplication/dto/.gitkeep
  src/main/java/com/pickple/server/api/moimapplication/repository/.gitkeep
  src/main/java/com/pickple/server/api/moimapplication/service/.gitkeep
  src/main/java/com/pickple/server/api/notice/controller/.gitkeep
  src/main/java/com/pickple/server/api/notice/domain/Notice.java
  src/main/java/com/pickple/server/api/notice/dto/.gitkeep
  src/main/java/com/pickple/server/api/notice/repository/.gitkeep
  src/main/java/com/pickple/server/api/notice/service/.gitkeep
  src/main/java/com/pickple/server/api/user/domain/User.java
  src/main/java/com/pickple/server/global/common/domain/BaseTimeEntity.java
Labels: 예린, feat

#13 [setting] S3 세팅
  build.gradle
  src/main/java/com/pickple/server/global/config/AwsConfig.java
Labels: setting, 예린

#15 [fix] 엔티티 수정
  src/main/java/com/pickple/server/api/applicant/domain/SubmitterState.java
  src/main/java/com/pickple/server/api/guest/domain/Guest.java
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/domain/enums/Category.java
  src/main/java/com/pickple/server/api/moim/domain/enums/MoimState.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/.gitkeep
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmission.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmissionState.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/.gitkeep
  src/main/java/com/pickple/server/api/moimsubmission/repository/.gitkeep
  src/main/java/com/pickple/server/api/moimsubmission/service/.gitkeep
  src/main/java/com/pickple/server/api/submitter/controller/.gitkeep
  src/main/java/com/pickple/server/api/submitter/domain/Submitter.java
  src/main/java/com/pickple/server/api/submitter/domain/SubmitterState.java
  src/main/java/com/pickple/server/api/submitter/dto/.gitkeep
  src/main/java/com/pickple/server/api/submitter/repository/.gitkeep
  src/main/java/com/pickple/server/api/submitter/service/.gitkeep
  src/main/java/com/pickple/server/api/user/domain/SocialType.java
Labels: fix, 예린

#22 [feat] 카테고리 전체 조회 API
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/enums/Category.java
  src/main/java/com/pickple/server/api/moim/dto/request/.gitkeep
  src/main/java/com/pickple/server/api/moim/dto/response/.gitkeep
  src/main/java/com/pickple/server/api/moim/service/.gitkeep
  src/main/java/com/pickple/server/api/moim/service/MoimService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat

#24 [feat] swagger 구현
  build.gradle
  src/main/java/com/pickple/server/api/user/controller/UserControllerDocs.java
  src/main/java/com/pickple/server/global/auth/client/dto/UserLoginRequest.java
  src/main/java/com/pickple/server/global/config/SecurityConfig.java
  src/main/java/com/pickple/server/global/config/SwaggerConfig.java
Labels: 보람, feat

#27 [feat] 모임 상세 조회 API 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/CategoryInfo.java
  src/main/java/com/pickple/server/api/moim/domain/DateInfo.java
  src/main/java/com/pickple/server/api/moim/domain/ImageInfo.java
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/domain/QuestionInfo.java
  src/main/java/com/pickple/server/api/moim/domain/enums/Category.java
  src/main/java/com/pickple/server/api/moim/dto/response/.gitkeep
  src/main/java/com/pickple/server/api/moim/dto/response/MoimDetailResponse.java
  src/main/java/com/pickple/server/api/moim/repository/.gitkeep
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/api/moim/service/MoimService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
  src/main/java/com/pickple/server/global/util/DateUtil.java
Labels: 예린, feat

#26 [feat] 호스트 승인 신청 API 구현
  src/main/java/com/pickple/server/api/TestController.java
  src/main/java/com/pickple/server/api/guest/repository/.gitkeep
  src/main/java/com/pickple/server/api/guest/repository/GuestRepository.java
  src/main/java/com/pickple/server/api/host/dto/.gitkeep
  src/main/java/com/pickple/server/api/submitter/controller/.gitkeep
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterController.java
  src/main/java/com/pickple/server/api/submitter/domain/Submitter.java
  src/main/java/com/pickple/server/api/submitter/domain/SubmitterCategoryInfo.java
  src/main/java/com/pickple/server/api/submitter/dto/.gitkeep
  src/main/java/com/pickple/server/api/submitter/dto/request/SubmitterCreateRequest.java
  src/main/java/com/pickple/server/api/submitter/repository/.gitkeep
  src/main/java/com/pickple/server/api/submitter/repository/SubmitterRepository.java
  src/main/java/com/pickple/server/api/submitter/service/.gitkeep
  src/main/java/com/pickple/server/api/submitter/service/SubmitterCommandService.java
  src/main/java/com/pickple/server/global/common/annotation/GuestId.java
  src/main/java/com/pickple/server/global/common/annotation/UserId.java
  src/main/java/com/pickple/server/global/common/annotation/resolver/GuestIdResolver.java
  src/main/java/com/pickple/server/global/common/annotation/resolver/UserIdResolver.java
  src/main/java/com/pickple/server/global/config/SecurityConfig.java
  src/main/java/com/pickple/server/global/config/WebConfig.java
  src/main/java/com/pickple/server/global/exception/BadRequestException.java
  src/main/java/com/pickple/server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 보람, feat

#30 [feat] 모임 참여 API 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/AccountInfo.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/AnswerInfo.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmission.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmissionState.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/.gitkeep
  src/main/java/com/pickple/server/api/moimsubmission/dto/request/MoimSubmitRequest.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/.gitkeep
  src/main/java/com/pickple/server/api/moimsubmission/repository/.gitkeep
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/.gitkeep
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat, Need to Refactor

#33 [feat] 신청한 모임 상세 정보 조회 API 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimDetailResponse.java
  src/main/java/com/pickple/server/api/moim/dto/response/SubmittedMoimResponse.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat

#35 [feat] S3 Pre-signed url을 사용한 파일 업로드 구현
  src/main/java/com/pickple/server/global/common/external/.gitkeep
  src/main/java/com/pickple/server/global/common/external/s3/PreSignedUrlResponse.java
  src/main/java/com/pickple/server/global/common/external/s3/S3BucketDirectory.java
  src/main/java/com/pickple/server/global/common/external/s3/S3Controller.java
  src/main/java/com/pickple/server/global/common/external/s3/S3ControllerDocs.java
  src/main/java/com/pickple/server/global/common/external/s3/S3Service.java
  src/main/java/com/pickple/server/global/config/AwsConfig.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 보람, 예린, feat, Need to Refactor

#36 [refactor] 모임 상세 정보 조회 API 리팩토링
  src/main/java/com/pickple/server/api/moim/dto/response/MoimDetailResponse.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
Labels: refactor, 예린

#38 [feat] 모임 개설 API 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/ImageInfo.java
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/dto/request/.gitkeep
  src/main/java/com/pickple/server/api/moim/dto/request/MoimCreateRequest.java
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat

#41 [feat] 공지사항 작성 API 구현
  src/main/java/com/pickple/server/api/notice/controller/.gitkeep
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
  src/main/java/com/pickple/server/api/notice/domain/Notice.java
  src/main/java/com/pickple/server/api/notice/dto/.gitkeep
  src/main/java/com/pickple/server/api/notice/dto/request/NoticeCreateRequest.java
  src/main/java/com/pickple/server/api/notice/repository/.gitkeep
  src/main/java/com/pickple/server/api/notice/repository/NoticeRepository.java
  src/main/java/com/pickple/server/api/notice/service/.gitkeep
  src/main/java/com/pickple/server/api/notice/service/NoticeCommandService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 보람, feat

#43 [feat] 카테고리에 해당하는 모임 조회 API 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimByCategoryResponse.java
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat, Need to Refactor

#45 [feat] 모임에 해당하는 소개 조회 API 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimDescriptionResponse.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat

#47 [feat] 모임에 해당하는 공지사항 전체 조회 API 구현
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
  src/main/java/com/pickple/server/api/notice/domain/Notice.java
  src/main/java/com/pickple/server/api/notice/dto/response/NoticeListGetByMoimResponse.java
  src/main/java/com/pickple/server/api/notice/repository/NoticeRepository.java
  src/main/java/com/pickple/server/api/notice/service/NoticeQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
  src/main/java/com/pickple/server/global/util/.gitkeep
  src/main/java/com/pickple/server/global/util/DateTimeUtil.java
Labels: 보람, feat

#48 [feat] 모임 질문 목록 조회 API 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat

#50 [fix] 회원가입 관련 수정
  src/main/java/com/pickple/server/api/guest/repository/GuestRepository.java
  src/main/java/com/pickple/server/api/user/dto/LoginSuccessResponse.java
  src/main/java/com/pickple/server/api/user/dto/TokenDto.java
  src/main/java/com/pickple/server/api/user/service/UserService.java
Labels: 보람, feat, Need to Refactor

#54 [feat] 게스트에 해당하는 신청한 모임 조회 API 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/dto/response/SubmittedMoimByGuestResponse.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/.gitkeep
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/SubmittedMoimByGuestResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat, Need to Refactor

#56 [feat] 모임에 해당하는 호스트 정보 조회 api 구현
  src/main/java/com/pickple/server/api/host/controller/HostController.java
  src/main/java/com/pickple/server/api/host/dto/response/HostByMoimResponse.java
  src/main/java/com/pickple/server/api/host/service/HostQueryService.java
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 보람, feat

#58 [feat] 게스트에 해당하는 참가한 모임 조회 API 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/MoimByGuestResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat

#60 [feat] 신청자에 해당하는 신청 내역 조회 api 구현
  src/main/java/com/pickple/server/api/host/dto/response/SubmittionDetailResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmission.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 보람, feat

#62 [fix] enum 참조 방식 수정
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/domain/enums/Category.java
  src/main/java/com/pickple/server/api/moim/domain/enums/MoimState.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimByCategoryResponse.java
  src/main/java/com/pickple/server/api/moim/dto/response/SubmittedMoimByGuestResponse.java
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmission.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmissionState.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/api/submitter/domain/Submitter.java
  src/main/java/com/pickple/server/api/submitter/domain/SubmitterCategoryInfo.java
  src/main/java/com/pickple/server/api/submitter/domain/SubmitterState.java
  src/main/java/com/pickple/server/api/submitter/repository/SubmitterRepository.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterCommandService.java
Labels: fix, 보람, 예린

#64 [feat] 신청자 승인 API 구현
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmission.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat

#66 [feat] 모임에 해당하는 신청자 전체 조회 api 구현
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/SubmitterInfo.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/MoimSubmissionByMoimResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 보람, feat

#68 [feat] 호스트에 해당하는 모임 조회 api 구현
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/enums/MoimState.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimListByHostGetResponse.java
  src/main/java/com/pickple/server/api/moim/repository/MoimRepository.java
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/MoimSubmissionState.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 보람, feat

#69 [docs] Swagger API 명세서 작성
  src/main/java/com/pickple/server/api/host/controller/HostController.java
  src/main/java/com/pickple/server/api/host/controller/HostControllerDocs.java
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/controller/MoimControllerDocs.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionControllerDocs.java
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
  src/main/java/com/pickple/server/api/notice/controller/NoticeControllerDocs.java
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterController.java
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterControllerDocs.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, docs

#71 [refactor] 신청자 승인 API 리팩토링
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/request/MoimSubmitterUpdateRequest.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
Labels: refactor, 예린

#73 [docs] Swagger API 명세서 미반영 부분 추가 작성
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionControllerDocs.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, docs

#75 [docs] 커스텀 어노테이션 관련 API 명세서 수정
  src/main/java/com/pickple/server/api/host/controller/HostControllerDocs.java
  src/main/java/com/pickple/server/api/moim/controller/MoimControllerDocs.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionControllerDocs.java
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterControllerDocs.java
Labels: 예린, docs

#78 [fix] GET API들의 ApiResponseDto 타입 지정
  src/main/java/com/pickple/server/api/host/controller/HostController.java
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/notice/controller/NoticeController.java
Labels: fix, 예린

#79 [fix] 호스트 승인 신청 시 중복 닉네임 방지 예외처리 추가
  src/main/java/com/pickple/server/api/host/repository/HostRepository.java
  src/main/java/com/pickple/server/api/submitter/repository/SubmitterRepository.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterCommandService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
Labels: fix, 예린

#81 [hotfix] 필수 requset 필드 수정
  src/main/java/com/pickple/server/api/moim/domain/CategoryInfo.java
  src/main/java/com/pickple/server/api/moim/domain/DateInfo.java
  src/main/java/com/pickple/server/api/moim/domain/ImageInfo.java
  src/main/java/com/pickple/server/api/moim/domain/QuestionInfo.java
  src/main/java/com/pickple/server/api/moim/dto/request/MoimCreateRequest.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/AccountInfo.java
  src/main/java/com/pickple/server/api/moimsubmission/domain/AnswerInfo.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/request/MoimSubmitRequest.java
  src/main/java/com/pickple/server/global/common/external/s3/S3Controller.java
Labels: hotfix, 예린

#83 [fix] 모임에 해당하는 신청자 전체 조회 api 수정
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/MoimSubmissionByMoimResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
Labels: fix, 보람

#85 [hotfix] 모임 중복 신청 예외처리 수정
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
Labels: hotfix, 예린

#88 [feat] 호스트 승인 신청 내역 조회 API 구현
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterController.java
  src/main/java/com/pickple/server/api/submitter/dto/response/SubmitterListGetResponse.java
  src/main/java/com/pickple/server/api/submitter/service/SubmitterQueryService.java
  src/main/java/com/pickple/server/global/response/enums/SuccessCode.java
Labels: 예린, feat

#89 [fix] 공지사항 조회 시 최신순으로 조회하도록 수정
  src/main/java/com/pickple/server/api/notice/repository/NoticeRepository.java
  src/main/java/com/pickple/server/api/notice/service/NoticeQueryService.java
Labels: fix, 예린

#91 [hotfix] 모임에 해당하는 신청자 전체 조회 API 로직 수정
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
Labels: hotfix, 예린

#93 [feat] guest 프로필 기본 이미지 설정
  src/main/java/com/pickple/server/api/user/service/UserService.java
Labels: 보람, feat

#96 [hotfix] 로그인시 host정보 불러오는 로직 수정
  src/main/java/com/pickple/server/api/host/repository/HostRepository.java
  src/main/java/com/pickple/server/api/user/service/UserService.java
Labels: hotfix, 보람

#101 [fix] 호스트 신청 내역 전체 조회에 관리자 권한 로직 추가
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterController.java
Labels: fix, 예린

#99 [docs] 호스트 신청 승인 관련 API 명세서 추가
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterControllerDocs.java
Labels: 예린, docs

#104 [fix] 모임 개설 후 리턴값으로 해당 모임 아이디 반환하도록 수정
  src/main/java/com/pickple/server/api/guest/domain/Guest.java
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/ImageInfo.java
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/dto/response/MoimCreateResponse.java
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/api/notice/domain/Notice.java
Labels: fix, 예린

#106 [fix] 관리자 검증 로직 수정
  src/main/java/com/pickple/server/api/submitter/controller/SubmitterController.java
Labels: fix, 예린

#108 [hotfix] 모임에 해당하는 신청자 전체 조회 시 모임명도 같이 반환하도록 수정
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/MoimSubmissionByMoimResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
Labels: hotfix, 예린

#110 [hotfix] 모임 신청자 승인 시 미승인자 상태 rejected로 변경
  src/main/java/com/pickple/server/api/host/domain/Host.java
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionController.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/api/submitter/domain/Submitter.java
Labels: hotfix, 예린, Need to Refactor

#113 [hotfix] 게스트 및 호스트 마이 클래스 모임 조회 시 빈 배열 처리 로직 수정
  src/main/java/com/pickple/server/api/moim/service/MoimQueryService.java
  src/main/java/com/pickple/server/api/moimsubmission/controller/MoimSubmissionControllerDocs.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
Labels: hotfix, 예린

#115 [hotfix] 모임 참여 신청 시 기본 상태값 변경
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
Labels: hotfix, 예린

#117 [hotfix] 이미지 없이 모임 생성되는 오류 수정
  src/main/java/com/pickple/server/api/moim/controller/MoimController.java
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/dto/request/MoimCreateRequest.java
Labels: hotfix, 🦊 예린

#119 [hotfix] 신청자 승인 시 승인 대기 상태만 승인 가능하도록 로직 수정
  src/main/java/com/pickple/server/api/moimsubmission/domain/SubmitterInfo.java
  src/main/java/com/pickple/server/api/moimsubmission/repository/MoimSubmissionRepository.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
Labels: hotfix, 🦊 예린

#120 [hotfix] 모임 신청자 관련 로직 수정
  src/main/java/com/pickple/server/api/moim/domain/Moim.java
  src/main/java/com/pickple/server/api/moim/service/MoimCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/dto/response/MoimSubmissionByMoimResponse.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionCommandService.java
  src/main/java/com/pickple/server/api/moimsubmission/service/MoimSubmissionQueryService.java
  src/main/java/com/pickple/server/global/response/enums/ErrorCode.java
  src/main/java/com/pickple/server/global/util/DateUtil.java
Labels: hotfix, 🦊 예린
